// Shared rendering of lib/features/finance/services/bank_logo_manifest.g.dart, used by
// tool/gen_bank_logo_manifest.dart (full map) and tool/strip_bank_logos.dart (empty map).

/// Relative path of the generated manifest.
const bankLogoManifestPath =
    'lib/features/finance/services/bank_logo_manifest.g.dart';

/// Relative path of the bundled logo directory (also the exact pubspec asset entry).
const bankLogoAssetDir = 'assets/bank_logos/';

/// Purpose: Render the manifest Dart source for a key → asset map.
/// Inputs: `assets` — preset key (`<country>/<id>`) → asset path; `stripped` marks a Store build.
/// Returns: `String` Dart source, entries sorted by key.
/// Side effects: None.
/// Notes: The output is deterministic so regenerating an unchanged set produces no diff.
String renderBankLogoManifest(
  Map<String, String> assets, {
  bool stripped = false,
}) {
  final keys = assets.keys.toList()..sort();
  final b = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_bank_logo_manifest.dart — do not edit by hand.',
    )
    ..writeln(
      '// Store builds: tool/strip_bank_logos.dart rewrites this map to empty before building.',
    )
    ..writeln(
      stripped
          ? '// This copy was stripped for a Store build: no bank logos are bundled.'
          : '// ${keys.length} bundled logos.',
    )
    ..writeln()
    ..writeln(
      '/// Purpose: Map a bank preset key (`<country>/<id>`) to its bundled logo asset.',
    )
    ..writeln('/// Inputs: None.')
    ..writeln('/// Returns: None (compile-time constant).')
    ..writeln('/// Side effects: None.')
    ..writeln(
      '/// Notes: Values are `assets/bank_logos/<country>_<id>.<svg|png>`. Empty in Store builds.',
    )
    ..writeln(
      '/// A listed asset can still fail to load, so callers must fall back to the network.',
    )
    ..write('const Map<String, String> bankLogoAssets = <String, String>{');
  if (keys.isEmpty) {
    b.writeln('};');
    return b.toString();
  }
  b.writeln();
  for (final k in keys) {
    b.writeln("  '$k': '${assets[k]}',");
  }
  b.writeln('};');
  return b.toString();
}
