/// Curated emoji keyword table for title-driven emoji suggestions.
library;

/// One suggestible emoji and its search keywords per language.
class EmojiKeywordEntry {
  final String emoji;
  final List<String> en;
  final List<String> zhHans;
  final List<String> zhHant;
  final List<String> ja;

  /// Purpose: Describe one suggestible emoji and its search keywords per language.
  /// Inputs: `emoji`; `en`, `zhHans`, `zhHant`, `ja` keyword lists (lowercase, trimmed).
  /// Returns: A new `EmojiKeywordEntry` instance.
  /// Side effects: None.
  /// Notes: Keywords of every language are matched regardless of the UI locale, the way an IME
  /// emoji search does; a test enforces lowercase, trimmed, non-empty keywords.
  const EmojiKeywordEntry(
    this.emoji, {
    this.en = const [],
    this.zhHans = const [],
    this.zhHant = const [],
    this.ja = const [],
  });

  /// Purpose: Return every keyword of every language as one iterable.
  /// Inputs: None.
  /// Returns: `Iterable<String>`.
  /// Side effects: None.
  /// Notes: None.
  Iterable<String> get allKeywords sync* {
    yield* en;
    yield* zhHans;
    yield* zhHant;
    yield* ja;
  }
}

/// Purpose: The curated emoji keyword table used by `suggestEmojis`.
/// Inputs: None.
/// Returns: None (top-level constant).
/// Side effects: None.
/// Notes: Table order is the tie-breaker for equal scores, so the more common reading of a
/// keyword goes first. Covers every emoji in `commonTaskEmojis` plus extras; each emoji appears
/// once. CJK keywords match as substrings, Latin keywords as whole tokens or phrases.
const List<EmojiKeywordEntry> emojiKeywordTable = [
  // ── Writing, study and work ──
  EmojiKeywordEntry(
    '📝',
    en: ['note', 'notes', 'memo', 'draft', 'todo', 'list', 'jot'],
    zhHans: ['笔记', '记录', '备忘', '草稿', '清单', '记下'],
    zhHant: ['筆記', '記錄', '備忘', '草稿', '清單', '記下'],
    ja: ['メモ', 'ノート', '記録', '下書き', 'めも', 'リスト'],
  ),
  EmojiKeywordEntry(
    '✍️',
    en: ['write', 'writing', 'essay', 'article', 'blog', 'journal', 'diary'],
    zhHans: ['写作', '写', '作文', '文章', '日记', '写作业'],
    zhHant: ['寫作', '寫', '作文', '文章', '日記', '寫作業'],
    ja: ['書く', '執筆', '作文', '日記', '記事', 'ブログ'],
  ),
  EmojiKeywordEntry(
    '📧',
    en: ['email', 'emails', 'e-mail', 'inbox', 'gmail', 'outlook'],
    zhHans: ['邮件', '电子邮件', '回邮件', '发邮件', '邮箱'],
    zhHant: ['郵件', '電子郵件', '回郵件', '寄郵件', '電郵'],
    ja: ['メール', 'めーる', 'eメール', '受信箱'],
  ),
  EmojiKeywordEntry(
    '✉️',
    en: ['mail', 'letter', 'letters', 'envelope', 'postcard'],
    zhHans: ['信件', '写信', '寄信', '信封', '明信片', '贺卡', '回信'],
    zhHant: ['信件', '寫信', '寄信', '信封', '明信片', '賀卡', '回信'],
    ja: ['手紙', '封筒', 'はがき', 'ハガキ', '葉書', '郵便', 'てがみ'],
  ),
  EmojiKeywordEntry(
    '📩',
    en: ['incoming', 'received', 'receive', 'newsletter'],
    zhHans: ['收到邮件', '收信', '收邮件'],
    zhHant: ['收到郵件', '收信', '收郵件'],
    ja: ['受信', '着信メール'],
  ),
  EmojiKeywordEntry(
    '📨',
    en: ['send', 'sent', 'invite', 'invitation', 'submit'],
    zhHans: ['发送', '发信', '邀请', '提交', '投递'],
    zhHant: ['發送', '寄出', '邀請', '提交', '投遞'],
    ja: ['送信', '送る', '招待', '提出'],
  ),
  EmojiKeywordEntry(
    '📮',
    en: ['postbox', 'post office', 'postal', 'stamp', 'stamps'],
    zhHans: ['邮局', '邮筒', '邮票', '挂号信'],
    zhHant: ['郵局', '郵筒', '郵票', '掛號信'],
    ja: ['郵便局', 'ポスト', '切手', '投函'],
  ),
  EmojiKeywordEntry(
    '📬',
    en: ['mailbox', 'check mail', 'pick up mail'],
    zhHans: ['信箱', '取信', '信报箱'],
    zhHant: ['信箱', '取信', '收信箱'],
    ja: ['郵便受け', 'ポスト確認', '郵便物'],
  ),
  EmojiKeywordEntry(
    '📖',
    en: ['read', 'reading', 'book', 'novel', 'chapter'],
    zhHans: ['看书', '读书', '阅读', '小说', '书籍'],
    zhHant: ['看書', '讀書', '閱讀', '小說', '書籍'],
    ja: ['読書', '本を読む', '読む', 'どくしょ', '小説'],
  ),
  EmojiKeywordEntry(
    '📚',
    en: ['books', 'library', 'borrow', 'textbook', 'reading list'],
    zhHans: ['图书馆', '借书', '还书', '课本', '书单'],
    zhHant: ['圖書館', '借書', '還書', '課本', '書單'],
    ja: ['図書館', '本', '教科書', '参考書', '借りる'],
  ),
  EmojiKeywordEntry(
    '🎓',
    en: [
      'study',
      'exam',
      'exams',
      'school',
      'class',
      'course',
      'lecture',
      'university',
      'college',
      'graduation',
      'learn',
      'learning',
      'homework',
      'thesis',
    ],
    zhHans: ['学习', '考试', '上课', '课程', '大学', '毕业', '复习', '作业', '论文', '预习'],
    zhHant: ['學習', '考試', '上課', '課程', '大學', '畢業', '複習', '作業', '論文', '預習'],
    ja: ['勉強', '試験', 'テスト', '授業', '大学', '卒業', '復習', '宿題', '論文', 'べんきょう'],
  ),
  EmojiKeywordEntry(
    '🧑‍🏫',
    en: ['teach', 'teaching', 'tutor', 'tutoring', 'lesson', 'lessons'],
    zhHans: ['教课', '家教', '辅导', '补习', '讲课'],
    zhHant: ['教課', '家教', '輔導', '補習', '講課'],
    ja: ['教える', '家庭教師', '塾', '講師', 'レッスン'],
  ),
  EmojiKeywordEntry(
    '🧠',
    en: ['memorize', 'vocabulary', 'vocab', 'flashcards', 'anki', 'brain'],
    zhHans: ['背单词', '单词', '记忆', '背诵', '思考'],
    zhHant: ['背單字', '單字', '記憶', '背誦', '思考'],
    ja: ['暗記', '単語', '記憶', '考える', '脳トレ'],
  ),
  EmojiKeywordEntry(
    '💼',
    en: [
      'work',
      'job',
      'business',
      'client',
      'clients',
      'interview',
      'project',
      'career',
    ],
    zhHans: ['工作', '上班', '会议', '开会', '客户', '面试', '项目', '出差', '加班'],
    zhHant: ['工作', '上班', '會議', '開會', '客戶', '面試', '專案', '出差', '加班'],
    ja: ['仕事', '会議', '出勤', '打ち合わせ', '面接', 'プロジェクト', '出張', '残業', 'しごと'],
  ),
  EmojiKeywordEntry(
    '🏢',
    en: ['office', 'company', 'building', 'headquarters'],
    zhHans: ['公司', '办公室', '写字楼', '大楼'],
    zhHant: ['公司', '辦公室', '大樓'],
    ja: ['会社', 'オフィス', '出社', 'ビル'],
  ),
  EmojiKeywordEntry(
    '👨‍💻',
    en: [
      'code',
      'coding',
      'program',
      'programming',
      'develop',
      'developer',
      'debug',
      'bug',
      'deploy',
      'github',
      'refactor',
    ],
    zhHans: ['编程', '写代码', '代码', '开发', '调试', '部署', '程序'],
    zhHant: ['程式', '寫程式', '程式碼', '開發', '除錯', '部署'],
    ja: ['プログラミング', 'コーディング', '開発', 'デバッグ', 'コード', '実装'],
  ),
  EmojiKeywordEntry(
    '💻',
    en: [
      'laptop',
      'computer',
      'pc',
      'mac',
      'online',
      'software',
      'website',
      'zoom',
    ],
    zhHans: ['电脑', '笔记本电脑', '上网', '软件', '装软件', '网站', '网课'],
    zhHant: ['電腦', '筆電', '上網', '軟體', '網站', '線上課程'],
    ja: ['パソコン', 'ノートパソコン', 'ソフト', 'ウェブサイト', 'オンライン', '在宅'],
  ),
  EmojiKeywordEntry(
    '📊',
    en: [
      'report',
      'data',
      'chart',
      'stats',
      'analytics',
      'spreadsheet',
      'excel',
      'presentation',
      'slides',
      'ppt',
    ],
    zhHans: ['数据', '报表', '图表', '统计', '分析', '表格', '汇报', '周报', '月报'],
    zhHant: ['數據', '報表', '圖表', '統計', '分析', '表格', '簡報', '週報', '月報'],
    ja: ['データ', '資料', 'グラフ', '集計', '分析', 'エクセル', '報告書', '週報'],
  ),
  EmojiKeywordEntry(
    '🗂️',
    en: [
      'organize',
      'file',
      'files',
      'documents',
      'paperwork',
      'archive',
      'folder',
    ],
    zhHans: ['整理文件', '文件', '资料', '归档', '文档'],
    zhHant: ['整理文件', '文件', '資料', '歸檔', '文檔'],
    ja: ['書類', 'ファイル', '資料整理', 'ファイリング'],
  ),
  EmojiKeywordEntry(
    '📄',
    en: [
      'document',
      'form',
      'forms',
      'application',
      'contract',
      'pdf',
      'resume',
      'cv',
    ],
    zhHans: ['表格', '申请', '简历', '合同', '申请表'],
    zhHant: ['表單', '申請', '履歷', '合約', '申請表'],
    ja: ['申請書', '履歴書', '契約書', '用紙', '申請'],
  ),
  EmojiKeywordEntry(
    '🖊️',
    en: ['sign', 'signature', 'fill in', 'fill out', 'pen'],
    zhHans: ['签字', '签名', '填表', '签合同'],
    zhHant: ['簽字', '簽名', '填表', '簽合約'],
    ja: ['署名', '記入', 'サイン', 'ペン'],
  ),
  EmojiKeywordEntry(
    '📎',
    en: ['attach', 'attachment', 'attachments', 'clip', 'paperclip'],
    zhHans: ['附件', '回形针', '附上'],
    zhHant: ['附件', '迴紋針', '附上'],
    ja: ['添付', 'クリップ', '添付ファイル'],
  ),
  EmojiKeywordEntry(
    '🖨️',
    en: ['print', 'printer', 'printing', 'scan', 'photocopy', 'copies'],
    zhHans: ['打印', '打印机', '复印', '扫描'],
    zhHant: ['列印', '印表機', '影印', '掃描'],
    ja: ['印刷', 'プリンター', 'コピー', 'スキャン', 'プリント'],
  ),
  EmojiKeywordEntry(
    '💡',
    en: [
      'idea',
      'ideas',
      'brainstorm',
      'inspiration',
      'light bulb',
      'lightbulb',
    ],
    zhHans: ['想法', '点子', '灵感', '创意', '头脑风暴', '灯泡'],
    zhHant: ['想法', '點子', '靈感', '創意', '腦力激盪', '燈泡'],
    ja: ['アイデア', 'アイディア', 'ひらめき', '発想', '企画', '電球'],
  ),
  EmojiKeywordEntry(
    '🔬',
    en: ['research', 'experiment', 'lab', 'science', 'analysis'],
    zhHans: ['研究', '实验', '科研', '实验室'],
    zhHant: ['研究', '實驗', '實驗室', '科研'],
    ja: ['研究', '実験', '実験室', 'ラボ'],
  ),
  EmojiKeywordEntry(
    '🎯',
    en: ['goal', 'goals', 'target', 'focus', 'objective', 'okr', 'kpi', 'plan'],
    zhHans: ['目标', '计划', '专注', '重点'],
    zhHant: ['目標', '計畫', '計劃', '專注', '重點'],
    ja: ['目標', '計画', '集中', 'もくひょう'],
  ),
  EmojiKeywordEntry(
    '📅',
    en: [
      'calendar',
      'schedule',
      'booking',
      'reservation',
      'date',
      'deadline',
    ],
    zhHans: ['日程', '日历', '预约', '安排', '截止', '行程'],
    zhHant: ['日程', '行事曆', '預約', '安排', '截止', '行程'],
    ja: ['予定', 'カレンダー', '予約', 'スケジュール', '締め切り', '日程'],
  ),
  EmojiKeywordEntry(
    '🤝',
    en: [
      'meet',
      'meeting',
      'meetup',
      'networking',
      'deal',
      'agreement',
      'negotiate',
    ],
    zhHans: ['见面', '面谈', '签约', '谈判', '合作'],
    zhHant: ['見面', '面談', '簽約', '談判', '合作'],
    ja: ['会う', '面談', '契約', '商談', '交渉'],
  ),
  EmojiKeywordEntry(
    '👥',
    en: ['team', 'group', 'colleagues', 'coworkers'],
    zhHans: ['团队', '小组', '同事', '团建'],
    zhHant: ['團隊', '小組', '同事'],
    ja: ['チーム', 'グループ', '同僚', '懇親会'],
  ),

  // ── Communication ──
  EmojiKeywordEntry(
    '☎️',
    en: ['call', 'phone call', 'telephone', 'ring', 'dial'],
    zhHans: ['打电话', '电话', '回电', '致电'],
    zhHant: ['打電話', '電話', '回電', '致電'],
    ja: ['電話', 'でんわ', '電話する', '連絡'],
  ),
  EmojiKeywordEntry(
    '📞',
    en: ['call back', 'hotline', 'customer service', 'support'],
    zhHans: ['回电话', '客服', '热线'],
    zhHant: ['回電話', '客服', '專線'],
    ja: ['折り返し', 'カスタマーサポート', 'サポート窓口'],
  ),
  EmojiKeywordEntry(
    '📱',
    en: ['phone', 'mobile', 'app', 'sms', 'iphone', 'android', 'top up'],
    zhHans: ['手机', '短信', '微信', '充话费', '换手机'],
    zhHant: ['手機', '簡訊', '儲值', '換手機'],
    ja: ['スマホ', '携帯', '機種変', 'アプリ', 'ライン'],
  ),
  EmojiKeywordEntry(
    '💬',
    en: ['chat', 'message', 'messages', 'text', 'talk', 'discuss', 'reply'],
    zhHans: ['聊天', '沟通', '讨论', '回复', '消息', '发消息'],
    zhHant: ['聊天', '溝通', '討論', '回覆', '訊息', '傳訊息'],
    ja: ['チャット', '相談', '話す', '返事', 'メッセージ', '返信'],
  ),
  EmojiKeywordEntry(
    '🗣️',
    en: ['speak', 'speaking', 'pronounce', 'pronunciation', 'conversation'],
    zhHans: ['口语', '练口语', '说话', '对话'],
    zhHant: ['口說', '練口說', '說話', '對話'],
    ja: ['会話', '英会話', '発音', 'スピーキング'],
  ),
  EmojiKeywordEntry(
    '🌐',
    en: [
      'translate',
      'translation',
      'language',
      'english',
      'japanese',
      'chinese',
    ],
    zhHans: ['翻译', '英语', '日语', '外语'],
    zhHant: ['翻譯', '英文', '日文', '外語'],
    ja: ['翻訳', '英語', '語学', '中国語', '通訳'],
  ),
  EmojiKeywordEntry(
    '🙏',
    en: [
      'thank',
      'thanks',
      'thank you',
      'grateful',
      'apologize',
      'sorry',
      'pray',
    ],
    zhHans: ['感谢', '谢谢', '道歉', '感恩'],
    zhHant: ['感謝', '謝謝', '道歉', '感恩'],
    ja: ['感謝', 'お礼', 'ありがとう', '謝る', 'お詫び'],
  ),
  EmojiKeywordEntry(
    '📰',
    en: ['news', 'newspaper', 'headlines'],
    zhHans: ['新闻', '看新闻', '报纸'],
    zhHant: ['新聞', '看新聞', '報紙'],
    ja: ['ニュース', '新聞'],
  ),

  // ── Arrows and status ──
  EmojiKeywordEntry(
    '➡️',
    en: [
      'next',
      'forward',
      'continue',
      'follow up',
      'followup',
      'proceed',
      'move on',
    ],
    zhHans: ['下一步', '继续', '跟进', '推进', '转交', '转发'],
    zhHant: ['下一步', '繼續', '跟進', '推進', '轉交', '轉寄'],
    ja: ['次へ', '進める', '続き', 'フォロー', '転送'],
  ),
  EmojiKeywordEntry(
    '⬅️',
    en: ['back', 'previous', 'go back', 'undo', 'revert'],
    zhHans: ['返回', '回退', '撤回', '上一步'],
    zhHant: ['返回', '回退', '撤回', '上一步'],
    ja: ['戻る', '前へ', '取り消し', 'もどる'],
  ),
  EmojiKeywordEntry(
    '⬆️',
    en: ['upload', 'increase', 'raise', 'upgrade', 'promote'],
    zhHans: ['上传', '升级', '提升', '增加'],
    zhHant: ['上傳', '升級', '提升', '增加'],
    ja: ['アップロード', '上げる', 'アップ', '昇格', '増やす'],
  ),
  EmojiKeywordEntry(
    '⬇️',
    en: ['download', 'decrease', 'reduce', 'lower', 'downgrade'],
    zhHans: ['下载', '降低', '减少', '降级'],
    zhHant: ['下載', '降低', '減少', '降級'],
    ja: ['ダウンロード', '下げる', '減らす'],
  ),
  EmojiKeywordEntry(
    '🔄',
    en: [
      'update',
      'sync',
      'refresh',
      'renew',
      'repeat',
      'redo',
      'retry',
      'backup',
      'restart',
      'reset',
      'subscription',
    ],
    zhHans: ['更新', '同步', '刷新', '续费', '重复', '重做', '备份', '重启', '续订'],
    zhHant: ['更新', '同步', '刷新', '續費', '重複', '重做', '備份', '重啟', '續訂'],
    ja: ['更新', '同期', '繰り返し', 'やり直し', 'バックアップ', '再起動', '継続'],
  ),
  EmojiKeywordEntry(
    '↩️',
    en: ['return', 'refund', 'give back', 'send back'],
    zhHans: ['退货', '退款', '归还', '退回', '还给'],
    zhHant: ['退貨', '退款', '歸還', '退回', '還給'],
    ja: ['返品', '返金', '返却', '返す', 'かえす'],
  ),
  EmojiKeywordEntry(
    '✅',
    en: [
      'done',
      'check',
      'complete',
      'finish',
      'confirm',
      'approve',
      'verify',
      'review',
    ],
    zhHans: ['完成', '确认', '检查', '核对', '审核', '打卡'],
    zhHant: ['完成', '確認', '檢查', '核對', '審核', '打卡'],
    ja: ['完了', '確認', 'チェック', '承認', 'レビュー'],
  ),
  EmojiKeywordEntry(
    '❗',
    en: ['urgent', 'important', 'asap', 'critical', 'priority', 'must'],
    zhHans: ['紧急', '重要', '马上', '尽快', '务必'],
    zhHant: ['緊急', '重要', '馬上', '盡快', '務必'],
    ja: ['緊急', '至急', '急ぎ', '大至急', '必ず', '重要'],
  ),
  EmojiKeywordEntry(
    '📌',
    // No "don't forget" / 别忘了 / 忘れずに: such filler opens many titles and would outrank the
    // object that follows it ("don't forget the keys" should suggest 🔑).
    en: ['pin', 'pinned', 'keep in mind'],
    zhHans: ['记住', '置顶'],
    zhHant: ['記住', '置頂'],
    ja: ['覚えておく', 'ピン留め', 'ピン'],
  ),
  EmojiKeywordEntry(
    '⭐',
    en: ['star', 'favorite', 'favourite', 'highlight', 'wishlist', 'rate'],
    zhHans: ['收藏', '星标', '心愿', '评价', '好评'],
    zhHant: ['收藏', '星號', '心願', '評價', '好評'],
    ja: ['お気に入り', '星', '評価', '欲しい物'],
  ),
  EmojiKeywordEntry(
    '🔔',
    en: ['notification', 'notify', 'bell', 'alert', 'subscribe'],
    zhHans: ['通知', '订阅'],
    zhHant: ['通知', '訂閱'],
    ja: ['通知', 'お知らせ'],
  ),
  EmojiKeywordEntry(
    '❓',
    en: ['question', 'questions', 'ask', 'faq', 'inquire', 'inquiry'],
    zhHans: ['问题', '提问', '询问', '请教'],
    zhHant: ['問題', '提問', '詢問', '請教'],
    ja: ['質問', '問い合わせ', '聞く', '疑問'],
  ),
  EmojiKeywordEntry(
    '🔍',
    en: ['search', 'find', 'look up', 'lookup', 'investigate', 'look for'],
    zhHans: ['搜索', '查找', '查询', '调查', '找'],
    zhHant: ['搜尋', '查找', '查詢', '調查', '找'],
    ja: ['検索', '調べる', '探す', '調査', 'しらべる'],
  ),
  EmojiKeywordEntry(
    '📍',
    en: ['location', 'address', 'place', 'visit'],
    zhHans: ['地址', '位置', '地点'],
    zhHant: ['地址', '位置', '地點'],
    ja: ['場所', '住所', '位置', '訪問'],
  ),

  // ── Time ──
  EmojiKeywordEntry(
    '⏰',
    en: ['alarm', 'wake up', 'wakeup', 'reminder', 'remind', 'timer', 'early'],
    zhHans: ['闹钟', '起床', '提醒', '早起', '定时'],
    zhHant: ['鬧鐘', '起床', '提醒', '早起', '定時'],
    ja: ['目覚まし', '起きる', '起床', 'リマインド', '早起き', 'アラーム'],
  ),
  EmojiKeywordEntry(
    '🕐',
    en: ['time', 'hour', 'clock', 'on time', 'punctual'],
    zhHans: ['时间', '准时', '几点', '小时'],
    zhHant: ['時間', '準時', '幾點', '小時'],
    ja: ['時間', '時刻', '定時'],
  ),
  EmojiKeywordEntry(
    '⏳',
    en: ['wait', 'waiting', 'pending', 'countdown', 'later'],
    zhHans: ['等待', '等候', '倒计时', '稍后'],
    zhHant: ['等待', '等候', '倒數', '稍後'],
    ja: ['待つ', '待ち', 'カウントダウン', '保留'],
  ),
  EmojiKeywordEntry(
    '🌅',
    en: ['morning', 'sunrise'],
    zhHans: ['早上', '清晨', '早晨', '日出'],
    zhHant: ['早上', '清晨', '早晨', '日出'],
    ja: ['朝', '早朝', '日の出', '朝活'],
  ),
  EmojiKeywordEntry(
    '🌙',
    en: ['night', 'evening', 'tonight', 'moon'],
    zhHans: ['晚上', '今晚', '夜里', '月亮'],
    zhHant: ['晚上', '今晚', '夜裡', '月亮'],
    ja: ['夜', '今夜', '夜中', '月'],
  ),

  // ── Delivery and shopping ──
  EmojiKeywordEntry(
    '📦',
    en: [
      'package',
      'packages',
      'parcel',
      'parcels',
      'delivery',
      'deliver',
      'shipping',
      'ship',
      'order',
      'amazon',
      'pickup',
      'pick up',
      'courier',
      'unbox',
    ],
    zhHans: [
      '快递',
      '包裹',
      '取快递',
      '收快递',
      '寄快递',
      '取件',
      '收货',
      '发货',
      '网购',
      '淘宝',
      '京东',
      '驿站',
    ],
    zhHant: [
      '快遞',
      '包裹',
      '取件',
      '收件',
      '寄件',
      '收貨',
      '出貨',
      '網購',
      '宅配',
      '蝦皮',
      '超商取貨',
    ],
    ja: [
      '荷物',
      '宅配',
      '配達',
      '受け取り',
      '発送',
      '通販',
      'アマゾン',
      '再配達',
      'にもつ',
      '小包',
      '宅急便',
    ],
  ),
  EmojiKeywordEntry(
    '🚚',
    en: ['truck', 'moving', 'movers', 'logistics', 'transport'],
    zhHans: ['搬家', '货车', '物流', '运输', '配送'],
    zhHant: ['搬家', '貨車', '物流', '運輸', '配送'],
    ja: ['引っ越し', 'トラック', '物流', '配送', '運送'],
  ),
  EmojiKeywordEntry(
    '🛒',
    en: [
      'shop',
      'shopping',
      'buy',
      'groceries',
      'grocery',
      'supermarket',
      'purchase',
    ],
    zhHans: ['购物', '买菜', '超市', '买东西', '采购', '购买'],
    zhHant: ['購物', '買菜', '超市', '買東西', '採購', '購買'],
    ja: ['買い物', '買う', 'スーパー', 'かいもの', '買い出し', '購入'],
  ),
  EmojiKeywordEntry(
    '🏪',
    en: ['convenience store', 'store', 'corner shop', '7-eleven'],
    zhHans: ['便利店', '小卖部', '商店'],
    zhHant: ['便利商店', '超商', '商店'],
    ja: ['コンビニ', '売店'],
  ),
  EmojiKeywordEntry(
    '🏬',
    en: ['mall', 'department store'],
    zhHans: ['商场', '百货', '逛街'],
    zhHant: ['商場', '百貨', '逛街'],
    ja: ['デパート', 'ショッピングモール', '百貨店'],
  ),
  EmojiKeywordEntry(
    '🏷️',
    en: ['sale', 'discount', 'coupon', 'coupons', 'label', 'tag', 'price'],
    zhHans: ['打折', '优惠', '优惠券', '促销', '标签'],
    zhHant: ['打折', '優惠', '優惠券', '促銷', '標籤'],
    ja: ['セール', '割引', 'クーポン', '値札', 'ラベル'],
  ),

  // ── Money ──
  EmojiKeywordEntry(
    '💰',
    en: [
      'money',
      'save',
      'savings',
      'budget',
      'salary',
      'cash',
      'income',
      'bonus',
    ],
    zhHans: ['钱', '存钱', '攒钱', '工资', '预算', '理财', '收入', '奖金', '现金'],
    zhHant: ['錢', '存錢', '薪水', '預算', '理財', '收入', '獎金', '現金'],
    ja: ['お金', '貯金', '給料', '予算', '現金', '収入', 'ボーナス', '節約'],
  ),
  EmojiKeywordEntry(
    '💳',
    en: [
      'card',
      'credit card',
      'bill',
      'bills',
      'payment',
      'pay',
      'repay',
      'installment',
    ],
    zhHans: ['信用卡', '还款', '账单', '付款', '刷卡', '缴费', '分期', '还信用卡'],
    zhHant: ['信用卡', '還款', '帳單', '付款', '刷卡', '繳費', '分期'],
    ja: ['クレジットカード', 'カード', '支払い', '請求', '引き落とし', '返済', '分割'],
  ),
  EmojiKeywordEntry(
    '🏦',
    en: ['bank', 'deposit', 'withdraw', 'loan', 'mortgage', 'transfer', 'atm'],
    zhHans: ['银行', '存款', '取钱', '贷款', '房贷', '转账', '开户'],
    zhHant: ['銀行', '存款', '領錢', '貸款', '房貸', '轉帳', '開戶'],
    ja: ['銀行', '振込', '預金', '引き出し', 'ローン', '口座', 'ぎんこう'],
  ),
  EmojiKeywordEntry(
    '🧾',
    en: [
      'receipt',
      'receipts',
      'invoice',
      'tax',
      'taxes',
      'expense',
      'expenses',
      'reimbursement',
    ],
    zhHans: ['发票', '报销', '收据', '报税', '缴税', '个税'],
    zhHant: ['發票', '報帳', '收據', '報稅', '繳稅'],
    ja: ['領収書', 'レシート', '請求書', '確定申告', '経費', '精算', '税金'],
  ),
  EmojiKeywordEntry(
    '💸',
    en: ['spend', 'lend', 'pay back', 'send money', 'wire'],
    zhHans: ['花钱', '转钱', '借钱', '还钱', '打钱'],
    zhHant: ['花錢', '轉錢', '借錢', '還錢'],
    ja: ['送金', '出費', '立て替え', '仕送り'],
  ),
  EmojiKeywordEntry(
    '📈',
    en: [
      'invest',
      'investment',
      'stock',
      'stocks',
      'fund',
      'funds',
      'portfolio',
      'crypto',
    ],
    zhHans: ['投资', '股票', '基金', '定投'],
    zhHant: ['投資', '股票', '基金', '定期定額'],
    ja: ['投資', '株', '株式', '投資信託', '積立', '新nisa'],
  ),
  EmojiKeywordEntry(
    '🪙',
    en: ['coin', 'coins', 'points', 'reward', 'rewards', 'cashback'],
    zhHans: ['积分', '硬币', '签到', '返现'],
    zhHant: ['積分', '點數', '硬幣', '簽到', '回饋'],
    ja: ['ポイント', '小銭', '硬貨', 'ポイ活'],
  ),
  EmojiKeywordEntry(
    '⚡',
    en: ['electricity', 'electric bill', 'power bill', 'utility', 'utilities'],
    zhHans: ['电费', '水电费', '交电费', '燃气费'],
    zhHant: ['電費', '水電費', '繳電費', '瓦斯費'],
    ja: ['電気代', '光熱費', '電気', '停電', 'ガス代'],
  ),
  EmojiKeywordEntry(
    '📶',
    en: [
      'wifi',
      'wi-fi',
      'internet',
      'router',
      'broadband',
      'network',
      'data plan',
    ],
    zhHans: ['网络', '宽带', '路由器', '流量', '网费'],
    zhHant: ['網路', '寬頻', '路由器', '網費'],
    ja: ['ネット', '回線', 'ルーター', '通信', 'ワイファイ'],
  ),

  // ── Gifts and events ──
  EmojiKeywordEntry(
    '🎁',
    en: ['gift', 'gifts', 'present', 'presents', 'wrap', 'surprise'],
    zhHans: ['礼物', '送礼', '礼品', '惊喜'],
    zhHant: ['禮物', '送禮', '禮品', '驚喜'],
    ja: ['プレゼント', '贈り物', 'ギフト', 'お土産', 'おみやげ'],
  ),
  EmojiKeywordEntry(
    '🎂',
    en: ['birthday', 'bday', 'cake', 'anniversary'],
    zhHans: ['生日', '蛋糕', '纪念日', '过生日'],
    zhHant: ['生日', '蛋糕', '紀念日', '過生日'],
    ja: ['誕生日', 'ケーキ', '記念日', 'たんじょうび', 'バースデー'],
  ),
  EmojiKeywordEntry(
    '🎉',
    en: [
      'party',
      'celebrate',
      'celebration',
      'festival',
      'congrats',
      'congratulations',
    ],
    zhHans: ['聚会', '派对', '庆祝', '节日'],
    zhHant: ['聚會', '派對', '慶祝', '節日'],
    ja: ['パーティー', 'お祝い', '祝い', '飲み会', '祭り'],
  ),
  EmojiKeywordEntry(
    '🎄',
    en: ['christmas', 'xmas'],
    zhHans: ['圣诞', '圣诞节'],
    zhHant: ['聖誕', '聖誕節'],
    ja: ['クリスマス'],
  ),
  EmojiKeywordEntry(
    '🧧',
    en: [
      'red envelope',
      'lunar new year',
      'spring festival',
      'chinese new year',
    ],
    zhHans: ['红包', '春节', '过年', '压岁钱'],
    zhHant: ['紅包', '春節', '過年', '壓歲錢'],
    ja: ['お年玉', '旧正月', '正月'],
  ),
  EmojiKeywordEntry(
    '💍',
    en: ['wedding', 'marry', 'engagement', 'ring', 'proposal', 'propose'],
    zhHans: ['婚礼', '结婚', '订婚', '求婚', '戒指'],
    zhHant: ['婚禮', '結婚', '訂婚', '求婚', '戒指'],
    ja: ['結婚式', '結婚', '婚約', '指輪', 'プロポーズ'],
  ),
  EmojiKeywordEntry(
    '🎟️',
    en: ['ticket', 'tickets', 'concert ticket', 'admission'],
    zhHans: ['门票', '抢票', '演出', '买票'],
    zhHant: ['門票', '搶票', '演出', '買票'],
    ja: ['チケット', '入場券', '公演'],
  ),

  // ── Health ──
  EmojiKeywordEntry(
    '🏥',
    en: ['hospital', 'doctor', 'clinic', 'surgery', 'emergency'],
    zhHans: ['医院', '看病', '看医生', '挂号', '门诊', '复诊', '手术'],
    zhHant: ['醫院', '看病', '看醫生', '掛號', '門診', '回診', '手術'],
    ja: ['病院', '通院', '診察', '手術', '受診', 'クリニック'],
  ),
  EmojiKeywordEntry(
    '🩺',
    en: [
      'checkup',
      'check up',
      'health check',
      'physical',
      'blood pressure',
      'diagnosis',
    ],
    zhHans: ['体检', '检查身体', '血压', '诊断'],
    zhHant: ['健檢', '健康檢查', '血壓', '診斷'],
    ja: ['健康診断', '健診', '検診', '血圧', '人間ドック', '検査'],
  ),
  EmojiKeywordEntry(
    '💊',
    en: [
      'medicine',
      'meds',
      'pill',
      'pills',
      'vitamin',
      'vitamins',
      'pharmacy',
      'prescription',
      'supplement',
      'supplements',
    ],
    zhHans: ['吃药', '药', '买药', '药店', '维生素', '处方', '药品', '保健品'],
    zhHant: ['吃藥', '藥', '買藥', '藥局', '維他命', '處方', '保健食品'],
    ja: ['薬', 'くすり', '服薬', '薬局', 'ビタミン', '処方箋', 'サプリ'],
  ),
  EmojiKeywordEntry(
    '💉',
    en: [
      'vaccine',
      'vaccination',
      'shot',
      'injection',
      'flu shot',
      'blood test',
      'booster',
    ],
    zhHans: ['疫苗', '打针', '接种', '抽血', '验血', '打疫苗'],
    zhHant: ['疫苗', '打針', '接種', '抽血', '驗血', '打疫苗'],
    ja: ['ワクチン', '予防接種', '注射', '採血', '血液検査'],
  ),
  EmojiKeywordEntry(
    '🦷',
    en: [
      'dentist',
      'dental',
      'teeth',
      'tooth',
      'floss',
      'brush teeth',
      'orthodontist',
      'braces',
    ],
    zhHans: ['牙医', '看牙', '洗牙', '刷牙', '牙齿', '补牙', '拔牙', '正畸'],
    zhHant: ['牙醫', '看牙', '洗牙', '刷牙', '牙齒', '補牙', '拔牙', '矯正'],
    ja: ['歯医者', '歯科', '歯磨き', '歯', '虫歯', '歯石', '歯列矯正'],
  ),
  EmojiKeywordEntry(
    '🧑‍⚕️',
    en: [
      'nurse',
      'physician',
      'therapist',
      'therapy',
      'consultation',
      'counseling',
    ],
    zhHans: ['医生', '护士', '心理咨询', '理疗', '复健'],
    zhHant: ['醫生', '護士', '心理諮商', '物理治療', '復健'],
    ja: ['医者', '医師', '看護師', 'カウンセリング', 'リハビリ'],
  ),
  EmojiKeywordEntry(
    '🤒',
    en: ['sick', 'ill', 'fever', 'flu', 'cold', 'cough', 'sick leave'],
    zhHans: ['生病', '发烧', '感冒', '咳嗽', '请病假'],
    zhHant: ['生病', '發燒', '感冒', '咳嗽', '請病假'],
    ja: ['風邪', '熱', '発熱', '咳', '体調不良', '病欠'],
  ),
  EmojiKeywordEntry(
    '👓',
    en: ['glasses', 'eye', 'eyes', 'optometrist', 'contacts', 'contact lenses'],
    zhHans: ['眼镜', '配眼镜', '眼科', '隐形眼镜', '视力'],
    zhHant: ['眼鏡', '配眼鏡', '眼科', '隱形眼鏡', '視力'],
    ja: ['眼鏡', 'メガネ', '眼科', 'コンタクト', '視力'],
  ),
  EmojiKeywordEntry(
    '💧',
    en: ['water', 'drink water', 'hydrate', 'hydration'],
    zhHans: ['喝水', '饮水', '补水'],
    zhHant: ['喝水', '飲水', '補水'],
    ja: ['水', '水分補給', '水を飲む', 'みず'],
  ),
  EmojiKeywordEntry(
    '💆',
    en: ['massage', 'spa', 'facial', 'skincare', 'skin care'],
    zhHans: ['按摩', '护肤', '面膜', '做脸', '美容'],
    zhHant: ['按摩', '保養', '護膚', '面膜', '美容'],
    ja: ['マッサージ', 'スキンケア', 'エステ', 'パック', '美容'],
  ),
  EmojiKeywordEntry(
    '💇',
    en: ['haircut', 'hair', 'barber', 'salon', 'hairdresser'],
    zhHans: ['理发', '剪头发', '剪发', '烫发', '染发', '头发'],
    zhHant: ['理髮', '剪頭髮', '剪髮', '燙髮', '染髮', '頭髮'],
    ja: ['美容院', '散髪', '床屋', 'ヘアカット', 'カット', '髪'],
  ),
  EmojiKeywordEntry(
    '⚖️',
    en: ['weigh', 'weight', 'scale', 'diet', 'weigh in'],
    zhHans: ['称重', '体重', '减肥', '节食'],
    zhHant: ['量體重', '體重', '減肥', '節食'],
    ja: ['体重', '体重計', 'ダイエット', '減量'],
  ),
  EmojiKeywordEntry(
    '🚭',
    en: ['quit smoking', 'no smoking'],
    zhHans: ['戒烟'],
    zhHant: ['戒菸'],
    ja: ['禁煙'],
  ),

  // ── Exercise ──
  EmojiKeywordEntry(
    '🏃',
    en: ['run', 'running', 'jog', 'jogging', 'marathon', 'cardio', '5k', '10k'],
    zhHans: ['跑步', '慢跑', '晨跑', '夜跑', '马拉松'],
    zhHant: ['跑步', '慢跑', '晨跑', '夜跑', '馬拉松'],
    ja: ['ランニング', 'ジョギング', '走る', 'はしる', 'マラソン'],
  ),
  EmojiKeywordEntry(
    '💪',
    en: [
      'workout',
      'exercise',
      'gym',
      'fitness',
      'strength',
      'pushup',
      'pushups',
      'situps',
      'plank',
    ],
    zhHans: ['锻炼', '健身', '运动', '俯卧撑', '仰卧起坐', '平板支撑', '肌肉'],
    zhHant: ['鍛鍊', '健身', '運動', '伏地挺身', '仰臥起坐', '平板支撐', '肌肉'],
    ja: ['筋トレ', '運動', 'トレーニング', '腕立て', '腹筋', 'うんどう', 'プランク'],
  ),
  EmojiKeywordEntry(
    '🏋️',
    en: [
      'weightlifting',
      'lift',
      'lifting',
      'squat',
      'squats',
      'deadlift',
      'bench press',
      'weights',
    ],
    zhHans: ['举铁', '深蹲', '硬拉', '卧推', '力量训练', '健身房'],
    zhHant: ['舉重', '重訓', '深蹲', '硬舉', '臥推', '健身房'],
    ja: ['ウエイト', 'スクワット', 'ジム', 'ベンチプレス', 'デッドリフト'],
  ),
  EmojiKeywordEntry(
    '🧘',
    en: [
      'yoga',
      'meditate',
      'meditation',
      'stretch',
      'stretching',
      'relax',
      'mindfulness',
      'breathe',
    ],
    zhHans: ['瑜伽', '冥想', '拉伸', '放松', '静坐'],
    zhHant: ['瑜伽', '冥想', '拉筋', '伸展', '放鬆', '靜坐'],
    ja: ['ヨガ', '瞑想', 'ストレッチ', 'めいそう', 'リラックス'],
  ),
  EmojiKeywordEntry(
    '🚶',
    en: ['walk', 'walking', 'steps', 'stroll'],
    zhHans: ['散步', '走路', '步行', '万步'],
    zhHant: ['散步', '走路', '步行', '萬步'],
    ja: ['散歩', 'ウォーキング', '歩く', 'さんぽ'],
  ),
  EmojiKeywordEntry(
    '🥾',
    en: ['hike', 'hiking', 'trek', 'trekking', 'mountain'],
    zhHans: ['徒步', '爬山', '登山'],
    zhHant: ['健行', '爬山', '登山'],
    ja: ['登山', 'ハイキング', '山登り'],
  ),
  EmojiKeywordEntry(
    '🏊',
    en: ['swim', 'swimming', 'pool'],
    zhHans: ['游泳', '泳池'],
    zhHant: ['游泳', '泳池'],
    ja: ['水泳', 'プール', '泳ぐ'],
  ),
  EmojiKeywordEntry(
    '🚲',
    en: ['bike', 'bicycle', 'cycle', 'cycling', 'ride'],
    zhHans: ['骑车', '自行车', '单车', '骑行'],
    zhHant: ['騎車', '腳踏車', '單車', '自行車'],
    ja: ['自転車', 'サイクリング', 'チャリ', 'じてんしゃ'],
  ),
  EmojiKeywordEntry(
    '⚽',
    en: ['football', 'soccer', 'match', 'sports'],
    zhHans: ['足球', '踢球', '球赛', '比赛'],
    zhHant: ['足球', '踢球', '球賽', '比賽'],
    ja: ['サッカー', '試合', 'フットサル'],
  ),
  EmojiKeywordEntry(
    '🏀',
    en: ['basketball', 'hoops'],
    zhHans: ['篮球', '打篮球'],
    zhHant: ['籃球', '打籃球'],
    ja: ['バスケ', 'バスケットボール'],
  ),
  EmojiKeywordEntry(
    '🏸',
    en: ['badminton'],
    zhHans: ['羽毛球'],
    zhHant: ['羽球', '羽毛球'],
    ja: ['バドミントン'],
  ),
  EmojiKeywordEntry(
    '🎾',
    en: ['tennis'],
    zhHans: ['网球'],
    zhHant: ['網球'],
    ja: ['テニス'],
  ),

  // ── Home chores ──
  EmojiKeywordEntry(
    '🧹',
    en: [
      'clean',
      'cleaning',
      'sweep',
      'tidy',
      'vacuum',
      'chores',
      'housework',
      'mop',
    ],
    zhHans: ['打扫', '扫地', '清洁', '整理', '大扫除', '拖地', '家务', '吸尘'],
    zhHant: ['打掃', '掃地', '清潔', '整理', '大掃除', '拖地', '家務', '吸塵'],
    ja: ['掃除', 'そうじ', '片付け', '掃除機', '家事', '整理'],
  ),
  EmojiKeywordEntry(
    '🧺',
    en: ['laundry', 'wash clothes', 'fold', 'folding', 'basket'],
    zhHans: ['洗衣服', '洗衣', '晾衣服', '收衣服', '叠衣服'],
    zhHant: ['洗衣服', '洗衣', '晾衣服', '收衣服', '摺衣服'],
    ja: ['洗濯', '洗濯物', '干す', '取り込む', '畳む', 'せんたく'],
  ),
  EmojiKeywordEntry(
    '👕',
    en: ['clothes', 'iron', 'ironing', 'dry cleaning', 'outfit', 'wardrobe'],
    zhHans: ['衣服', '熨衣服', '干洗', '换季', '衣柜'],
    zhHant: ['衣服', '燙衣服', '乾洗', '換季', '衣櫃'],
    ja: ['服', 'アイロン', 'クリーニング', '衣替え', 'クローゼット'],
  ),
  EmojiKeywordEntry(
    '🧼',
    en: ['soap', 'wash hands', 'handwash', 'disinfect', 'sanitize', 'scrub'],
    zhHans: ['洗手', '消毒', '肥皂', '洗手液'],
    zhHant: ['洗手', '消毒', '肥皂', '洗手乳'],
    ja: ['石鹸', '手洗い', '消毒', '除菌'],
  ),
  EmojiKeywordEntry(
    '🚿',
    en: ['shower', 'bathroom', 'toilet', 'clean bathroom'],
    zhHans: ['洗澡', '淋浴', '浴室', '厕所', '卫生间'],
    zhHant: ['洗澡', '淋浴', '浴室', '廁所', '衛浴'],
    ja: ['シャワー', '風呂掃除', '浴室', 'トイレ'],
  ),
  EmojiKeywordEntry(
    '🛁',
    en: ['bath', 'bathtub', 'soak', 'hot spring'],
    zhHans: ['泡澡', '浴缸', '温泉'],
    zhHant: ['泡澡', '浴缸', '溫泉'],
    ja: ['お風呂', '入浴', '風呂', '温泉', '湯船'],
  ),
  EmojiKeywordEntry(
    '🛏️',
    en: ['bed', 'make bed', 'sheets', 'bedding', 'change sheets', 'mattress'],
    zhHans: ['铺床', '床单', '换床单', '被子', '晒被子', '床'],
    zhHant: ['鋪床', '床單', '換床單', '被子', '曬被子', '床'],
    ja: ['ベッド', 'シーツ', '布団', '寝具', 'ふとん', '布団干し'],
  ),
  EmojiKeywordEntry(
    '🗑️',
    en: [
      'trash',
      'garbage',
      'rubbish',
      'take out trash',
      'bin',
      'throw away',
      'declutter',
    ],
    zhHans: ['倒垃圾', '垃圾', '扔垃圾', '垃圾分类', '丢掉', '断舍离'],
    zhHant: ['倒垃圾', '垃圾', '丟垃圾', '垃圾分類', '丟掉', '斷捨離'],
    ja: ['ゴミ', 'ごみ', 'ゴミ出し', 'ごみ出し', '捨てる', '断捨離', '粗大ごみ'],
  ),
  EmojiKeywordEntry(
    '♻️',
    en: ['recycle', 'recycling', 'reuse', 'compost'],
    zhHans: ['回收', '可回收', '废品', '旧物'],
    zhHant: ['回收', '資源回收', '廢品', '舊物'],
    ja: ['リサイクル', '資源ごみ', '分別', '再利用'],
  ),
  EmojiKeywordEntry(
    '🧻',
    en: ['toilet paper', 'tissue', 'tissues', 'paper towel', 'paper towels'],
    zhHans: ['卫生纸', '纸巾', '抽纸'],
    zhHant: ['衛生紙', '面紙', '紙巾'],
    ja: ['トイレットペーパー', 'ティッシュ', 'キッチンペーパー'],
  ),
  EmojiKeywordEntry(
    '🧴',
    en: ['shampoo', 'lotion', 'toiletries', 'body wash', 'conditioner'],
    zhHans: ['洗发水', '沐浴露', '乳液', '日用品', '护发素'],
    zhHant: ['洗髮精', '沐浴乳', '乳液', '日用品', '潤髮乳'],
    ja: ['シャンプー', '化粧水', '日用品', '乳液', 'ボディソープ'],
  ),
  EmojiKeywordEntry(
    '🔧',
    en: [
      'fix',
      'repair',
      'maintenance',
      'maintain',
      'wrench',
      'install',
      'assemble',
    ],
    zhHans: ['修理', '维修', '安装', '组装', '保养'],
    zhHant: ['修理', '維修', '安裝', '組裝', '保養'],
    ja: ['修理', '直す', '取り付け', '組み立て', 'メンテナンス'],
  ),
  EmojiKeywordEntry(
    '🛠️',
    en: [
      'tools',
      'diy',
      'build',
      'toolbox',
      'handyman',
      'renovate',
      'renovation',
    ],
    zhHans: ['工具', '动手', '装修', '手工'],
    zhHant: ['工具', '裝修', '手工', '動手做'],
    ja: ['工具', '日曜大工', '工作', 'リフォーム'],
  ),
  EmojiKeywordEntry(
    '🔑',
    en: ['key', 'keys', 'lock', 'password', 'spare key', 'locksmith'],
    zhHans: ['钥匙', '配钥匙', '密码', '门锁'],
    zhHant: ['鑰匙', '打鑰匙', '密碼', '門鎖'],
    ja: ['鍵', '合鍵', 'パスワード', '暗証番号', 'かぎ'],
  ),
  EmojiKeywordEntry(
    '🔒',
    en: ['security', 'privacy', '2fa', 'encrypt', 'encryption'],
    zhHans: ['安全', '隐私', '加密'],
    zhHant: ['安全', '隱私', '加密'],
    ja: ['セキュリティ', 'プライバシー', '暗号化'],
  ),
  EmojiKeywordEntry(
    '🔋',
    en: ['charge', 'charging', 'battery', 'charger', 'power bank'],
    zhHans: ['充电', '电池', '充电宝', '换电池'],
    zhHant: ['充電', '電池', '行動電源', '換電池'],
    ja: ['充電', '電池', 'バッテリー', 'モバイルバッテリー', '充電器'],
  ),
  EmojiKeywordEntry(
    '🏠',
    en: ['home', 'house', 'rent', 'apartment', 'landlord', 'household'],
    zhHans: ['回家', '房租', '房子', '租房', '房东', '交房租'],
    zhHant: ['回家', '房租', '房子', '租屋', '房東', '繳房租'],
    ja: ['家', '帰宅', '家賃', '自宅', 'いえ', '大家'],
  ),

  // ── Family and pets ──
  EmojiKeywordEntry(
    '👶',
    en: [
      'baby',
      'diaper',
      'diapers',
      'kid',
      'kids',
      'child',
      'children',
      'daycare',
    ],
    zhHans: ['宝宝', '婴儿', '尿布', '孩子', '带娃', '喂奶', '纸尿裤'],
    zhHant: ['寶寶', '嬰兒', '尿布', '孩子', '帶小孩', '餵奶'],
    ja: ['赤ちゃん', '子供', 'おむつ', '育児', '保育園', '授乳', 'こども'],
  ),
  EmojiKeywordEntry(
    '👪',
    en: ['family', 'parents', 'mom', 'dad', 'mother', 'father', 'relatives'],
    zhHans: ['家人', '家庭', '父母', '爸妈', '妈妈', '爸爸', '亲戚'],
    zhHant: ['家人', '家庭', '父母', '爸媽', '媽媽', '爸爸', '親戚'],
    ja: ['家族', '両親', '実家', 'お母さん', 'お父さん', '親戚'],
  ),
  EmojiKeywordEntry(
    '🏫',
    en: [
      'kindergarten',
      'parent meeting',
      'pick up kids',
      'teacher',
      'school run',
    ],
    zhHans: ['学校', '幼儿园', '家长会', '接孩子', '老师', '送孩子'],
    zhHant: ['學校', '幼兒園', '幼稚園', '家長會', '接小孩', '老師'],
    ja: ['学校', '幼稚園', '保護者会', '送り迎え', '先生', '授業参観'],
  ),
  EmojiKeywordEntry(
    '❤️',
    en: [
      'love',
      'dating',
      'partner',
      'girlfriend',
      'boyfriend',
      'wife',
      'husband',
      'romantic',
    ],
    zhHans: ['约会', '女朋友', '男朋友', '老婆', '老公', '恋爱'],
    zhHant: ['約會', '女朋友', '男朋友', '老婆', '老公', '戀愛'],
    ja: ['デート', '恋人', '彼女', '彼氏', '妻', '夫', '愛'],
  ),
  EmojiKeywordEntry(
    '🐕',
    en: ['dog', 'dogs', 'walk the dog', 'puppy'],
    zhHans: ['遛狗', '狗', '小狗', '狗粮'],
    zhHant: ['遛狗', '狗', '小狗', '狗糧'],
    ja: ['犬', 'いぬ', 'ワンちゃん', 'ドッグフード', '犬の散歩'],
  ),
  EmojiKeywordEntry(
    '🐈',
    en: ['cat', 'cats', 'kitten', 'litter', 'cat food'],
    zhHans: ['猫', '猫粮', '猫砂', '铲屎', '喂猫'],
    zhHant: ['貓', '貓糧', '貓砂', '鏟屎', '餵貓'],
    ja: ['猫', 'ねこ', 'ネコ', '猫砂', 'キャットフード'],
  ),
  EmojiKeywordEntry(
    '🐾',
    en: ['pet', 'pets', 'vet', 'grooming', 'pet food'],
    zhHans: ['宠物', '兽医', '宠物医院'],
    zhHant: ['寵物', '獸醫', '動物醫院'],
    ja: ['ペット', '動物病院', '獣医', 'トリミング'],
  ),
  EmojiKeywordEntry(
    '🐟',
    en: ['fish', 'aquarium', 'feed fish', 'seafood'],
    zhHans: ['鱼', '喂鱼', '鱼缸', '海鲜'],
    zhHant: ['魚', '餵魚', '魚缸', '海鮮'],
    ja: ['魚', '金魚', '水槽', '刺身', '鮮魚'],
  ),
  EmojiKeywordEntry(
    '🐦',
    en: ['bird', 'birds', 'parrot'],
    zhHans: ['鸟', '鹦鹉'],
    zhHant: ['鳥', '鸚鵡'],
    ja: ['鳥', 'インコ'],
  ),
  EmojiKeywordEntry(
    '🪴',
    en: ['plant', 'plants', 'water plants', 'repot', 'houseplant'],
    zhHans: ['浇花', '浇水', '植物', '盆栽', '花草'],
    zhHant: ['澆花', '澆水', '植物', '盆栽', '花草'],
    ja: ['水やり', '観葉植物', '植物', '植え替え', '鉢'],
  ),
  EmojiKeywordEntry(
    '🌱',
    en: [
      'seed',
      'seeds',
      'sow',
      'grow',
      'sprout',
      'garden',
      'gardening',
      'habit',
    ],
    zhHans: ['种菜', '种植', '发芽', '播种', '园艺', '习惯'],
    zhHant: ['種菜', '種植', '發芽', '播種', '園藝', '習慣'],
    ja: ['種', '家庭菜園', '園芸', '芽', '習慣', 'ガーデニング'],
  ),
  EmojiKeywordEntry(
    '💐',
    en: ['flowers', 'bouquet', 'florist'],
    zhHans: ['鲜花', '花束', '买花', '送花'],
    zhHant: ['鮮花', '花束', '買花', '送花'],
    ja: ['花束', '花', 'お花', '花屋', 'ブーケ'],
  ),

  // ── Transport and travel ──
  EmojiKeywordEntry(
    '🚗',
    en: [
      'car',
      'drive',
      'driving',
      'carwash',
      'car wash',
      'commute',
      'drop off',
    ],
    zhHans: ['开车', '汽车', '洗车', '年检', '接送', '驾照', '车险'],
    zhHant: ['開車', '汽車', '洗車', '驗車', '接送', '車險'],
    ja: ['車', '運転', '洗車', '車検', '送迎', 'くるま', 'ドライブ'],
  ),
  EmojiKeywordEntry(
    '🚌',
    en: ['bus', 'shuttle'],
    zhHans: ['公交', '公交车', '巴士', '坐车', '通勤'],
    zhHant: ['公車', '巴士', '客運', '通勤'],
    ja: ['バス', '通勤', '通学'],
  ),
  EmojiKeywordEntry(
    '🚆',
    en: ['train', 'subway', 'metro', 'rail', 'station'],
    zhHans: ['火车', '高铁', '地铁', '动车', '车票', '车站'],
    zhHant: ['火車', '高鐵', '捷運', '車票', '車站'],
    ja: ['電車', '新幹線', '地下鉄', '駅', '切符', '定期券'],
  ),
  EmojiKeywordEntry(
    '🚕',
    en: ['taxi', 'cab', 'uber', 'lyft'],
    zhHans: ['打车', '出租车', '滴滴'],
    zhHant: ['叫車', '計程車', '搭計程車'],
    ja: ['タクシー'],
  ),
  EmojiKeywordEntry(
    '⛽',
    en: ['gas', 'fuel', 'refuel', 'gas station', 'petrol', 'fill up'],
    zhHans: ['加油', '加油站', '油费'],
    zhHant: ['加油', '加油站', '油錢'],
    ja: ['給油', 'ガソリン', 'ガソリンスタンド', '満タン'],
  ),
  EmojiKeywordEntry(
    '🅿️',
    en: ['parking', 'parking lot', 'garage'],
    zhHans: ['停车', '停车场', '停车费', '车位'],
    zhHant: ['停車', '停車場', '停車費', '車位'],
    ja: ['駐車', '駐車場', 'パーキング', '駐車料金'],
  ),
  EmojiKeywordEntry(
    '✈️',
    en: [
      'flight',
      'fly',
      'travel',
      'trip',
      'airport',
      'plane',
      'vacation',
      'holiday',
      'boarding',
    ],
    zhHans: ['机票', '航班', '旅行', '旅游', '出行', '机场', '飞机', '度假'],
    zhHant: ['機票', '航班', '旅行', '旅遊', '機場', '飛機', '度假'],
    ja: ['飛行機', '旅行', 'フライト', '空港', '航空券', '旅', 'りょこう'],
  ),
  EmojiKeywordEntry(
    '🧳',
    en: ['pack', 'packing', 'luggage', 'suitcase', 'business trip'],
    zhHans: ['行李', '收拾行李', '行李箱'],
    zhHant: ['行李', '收拾行李', '行李箱'],
    ja: ['荷造り', 'スーツケース', '旅支度'],
  ),
  EmojiKeywordEntry(
    '🏨',
    en: [
      'hotel',
      'check in',
      'check-in',
      'check out',
      'accommodation',
      'airbnb',
    ],
    zhHans: ['酒店', '宾馆', '订酒店', '入住', '退房', '民宿'],
    zhHant: ['飯店', '旅館', '訂房', '入住', '退房', '民宿'],
    ja: ['ホテル', '宿', 'チェックイン', 'チェックアウト', '旅館'],
  ),
  EmojiKeywordEntry(
    '🛂',
    en: ['passport', 'visa', 'immigration', 'customs'],
    zhHans: ['护照', '签证', '办签证', '出入境'],
    zhHant: ['護照', '簽證', '辦簽證', '出入境'],
    ja: ['パスポート', 'ビザ', '査証', '入国'],
  ),
  EmojiKeywordEntry(
    '🗺️',
    en: ['map', 'route', 'itinerary', 'explore', 'sightseeing'],
    zhHans: ['地图', '路线', '攻略', '行程规划'],
    zhHant: ['地圖', '路線', '攻略', '行程規劃'],
    ja: ['地図', 'ルート', '旅程', '観光'],
  ),
  EmojiKeywordEntry(
    '🪪',
    en: [
      'id',
      'id card',
      'license',
      'licence',
      'driver license',
      'driving licence',
    ],
    zhHans: ['身份证', '证件', '驾驶证', '补办'],
    zhHant: ['身分證', '證件', '駕照', '補辦'],
    ja: ['免許証', 'マイナンバー', '身分証', '保険証', '住民票'],
  ),

  // ── Places ──
  EmojiKeywordEntry(
    '⛪',
    en: ['church', 'mass', 'worship', 'sunday service'],
    zhHans: ['教堂', '礼拜', '做礼拜', '祷告'],
    zhHant: ['教堂', '禮拜', '做禮拜', '禱告'],
    ja: ['教会', '礼拝', 'ミサ'],
  ),
  EmojiKeywordEntry(
    '⛩️',
    en: ['shrine', 'temple'],
    zhHans: ['神社', '寺庙', '拜拜', '上香'],
    zhHant: ['神社', '寺廟', '拜拜', '上香'],
    ja: ['神社', 'お寺', '参拝', '初詣', 'お参り'],
  ),
  EmojiKeywordEntry(
    '🏛️',
    en: ['museum', 'government', 'city hall', 'embassy', 'court', 'consulate'],
    zhHans: ['博物馆', '政府', '办事处', '大使馆', '法院', '领事馆'],
    zhHant: ['博物館', '政府', '區公所', '大使館', '法院', '領事館'],
    ja: ['博物館', '役所', '市役所', '区役所', '大使館', '裁判所'],
  ),

  // ── Leisure ──
  EmojiKeywordEntry(
    '🎵',
    en: ['music', 'song', 'songs', 'playlist', 'concert'],
    zhHans: ['音乐', '歌曲', '演唱会', '听歌'],
    zhHant: ['音樂', '歌曲', '演唱會', '聽歌'],
    ja: ['音楽', '歌', 'ライブ', 'コンサート'],
  ),
  EmojiKeywordEntry(
    '🎹',
    en: ['piano', 'keyboard'],
    zhHans: ['钢琴', '练琴'],
    zhHant: ['鋼琴', '練琴'],
    ja: ['ピアノ'],
  ),
  EmojiKeywordEntry(
    '🎸',
    en: ['guitar', 'band', 'bass'],
    zhHans: ['吉他', '乐队', '贝斯'],
    zhHant: ['吉他', '樂團', '貝斯'],
    ja: ['ギター', 'バンド', 'ベース'],
  ),
  EmojiKeywordEntry(
    '🎤',
    en: ['karaoke', 'ktv', 'sing', 'singing', 'speech'],
    zhHans: ['唱歌', '演讲', '发言', '唱k'],
    zhHant: ['唱歌', '演講', '發言', '唱k'],
    ja: ['カラオケ', 'スピーチ', '発表', '講演'],
  ),
  EmojiKeywordEntry(
    '🎧',
    en: ['podcast', 'podcasts', 'listen', 'headphones', 'audiobook'],
    zhHans: ['播客', '耳机', '有声书'],
    zhHant: ['播客', '耳機', '有聲書'],
    ja: ['ポッドキャスト', 'イヤホン', 'ヘッドホン', '聴く', 'オーディオブック'],
  ),
  EmojiKeywordEntry(
    '🎨',
    en: [
      'draw',
      'drawing',
      'paint',
      'painting',
      'art',
      'design',
      'sketch',
      'illustration',
    ],
    zhHans: ['画画', '绘画', '画', '设计', '素描', '插画'],
    zhHant: ['畫畫', '繪畫', '畫', '設計', '素描', '插畫'],
    ja: ['絵', '描く', 'お絵描き', 'デザイン', 'イラスト', '絵画'],
  ),
  EmojiKeywordEntry(
    '📸',
    en: [
      'photo',
      'photos',
      'picture',
      'pictures',
      'camera',
      'photography',
      'selfie',
    ],
    zhHans: ['拍照', '照片', '摄影', '相机', '照相'],
    zhHant: ['拍照', '照片', '攝影', '相機', '照相'],
    ja: ['写真', '撮影', 'カメラ', 'しゃしん'],
  ),
  EmojiKeywordEntry(
    '🎥',
    en: ['video', 'videos', 'record', 'recording', 'vlog'],
    zhHans: ['录像', '视频', '剪视频', '拍视频', '录制'],
    zhHant: ['錄影', '影片', '剪片', '拍影片', '錄製'],
    ja: ['動画', '録画', '動画編集', 'ビデオ'],
  ),
  EmojiKeywordEntry(
    '🎬',
    en: ['movie', 'movies', 'film', 'cinema', 'theater', 'theatre', 'netflix'],
    zhHans: ['电影', '看电影', '影院', '追剧'],
    zhHant: ['電影', '看電影', '電影院', '追劇'],
    ja: ['映画', '映画館', 'ドラマ', '観る'],
  ),
  EmojiKeywordEntry(
    '📺',
    en: ['tv', 'show', 'series', 'episode', 'anime', 'youtube', 'stream'],
    zhHans: ['电视', '看剧', '电视剧', '综艺', '番剧', '动漫'],
    zhHant: ['電視', '看劇', '電視劇', '綜藝', '動畫', '動漫'],
    ja: ['テレビ', 'アニメ', '番組', '配信', 'ユーチューブ'],
  ),
  EmojiKeywordEntry(
    '🎮',
    en: [
      'game',
      'games',
      'gaming',
      'play',
      'playstation',
      'xbox',
      'nintendo',
      'steam',
    ],
    zhHans: ['游戏', '打游戏', '玩游戏', '电玩'],
    zhHant: ['遊戲', '打電動', '玩遊戲', '電玩'],
    ja: ['ゲーム', 'ゲームする', 'プレイ'],
  ),
  EmojiKeywordEntry(
    '🎲',
    en: ['board game', 'boardgame', 'board games', 'dice', 'tabletop'],
    zhHans: ['桌游', '骰子', '麻将'],
    zhHant: ['桌遊', '骰子', '麻將'],
    ja: ['ボードゲーム', 'サイコロ', '麻雀'],
  ),
  EmojiKeywordEntry(
    '🧩',
    en: ['puzzle', 'puzzles', 'jigsaw', 'crossword', 'sudoku'],
    zhHans: ['拼图', '谜题', '数独'],
    zhHant: ['拼圖', '謎題', '數獨'],
    ja: ['パズル', 'ジグソー', '数独', 'クロスワード'],
  ),
  EmojiKeywordEntry(
    '🧸',
    en: ['toy', 'toys', 'teddy'],
    zhHans: ['玩具', '玩偶'],
    zhHant: ['玩具', '玩偶'],
    ja: ['おもちゃ', 'ぬいぐるみ'],
  ),

  // ── Food and drink ──
  EmojiKeywordEntry(
    '🍳',
    en: ['cook', 'cooking', 'breakfast', 'fry', 'recipe', 'meal prep'],
    zhHans: ['做饭', '烹饪', '早餐', '早饭', '煎蛋', '下厨', '菜谱'],
    zhHant: ['做飯', '煮飯', '烹飪', '早餐', '煎蛋', '下廚', '食譜'],
    ja: ['料理', '朝ごはん', '朝食', '自炊', 'レシピ', '目玉焼き'],
  ),
  EmojiKeywordEntry(
    '🧑‍🍳',
    en: ['chef', 'bake', 'baking', 'kitchen'],
    zhHans: ['厨师', '做菜', '烘焙', '厨房'],
    zhHant: ['廚師', '做菜', '烘焙', '廚房'],
    ja: ['シェフ', '料理人', 'お菓子作り', 'キッチン', '台所'],
  ),
  EmojiKeywordEntry(
    '🍽️',
    en: [
      'dinner',
      'lunch',
      'meal',
      'eat',
      'restaurant',
      'dishes',
      'wash dishes',
      'dine',
    ],
    zhHans: ['吃饭', '午饭', '晚饭', '午餐', '晚餐', '聚餐', '餐厅', '洗碗'],
    zhHant: ['吃飯', '午飯', '晚飯', '午餐', '晚餐', '聚餐', '餐廳', '洗碗'],
    ja: ['ご飯', '昼ごはん', '晩ごはん', '昼食', '夕食', 'ランチ', 'ディナー', '食事', '皿洗い', '外食'],
  ),
  EmojiKeywordEntry(
    '🥗',
    en: ['salad', 'healthy', 'vegetables', 'veggies', 'eat healthy'],
    zhHans: ['沙拉', '轻食', '健康饮食', '蔬菜'],
    zhHant: ['沙拉', '輕食', '健康飲食', '蔬菜'],
    ja: ['サラダ', '野菜', 'ヘルシー'],
  ),
  EmojiKeywordEntry(
    '🍎',
    en: ['fruit', 'fruits', 'apple', 'apples', 'snack', 'snacks'],
    zhHans: ['水果', '苹果', '买水果', '零食'],
    zhHant: ['水果', '蘋果', '買水果', '零食'],
    ja: ['果物', 'りんご', 'リンゴ', 'フルーツ', 'おやつ'],
  ),
  EmojiKeywordEntry(
    '🥛',
    en: ['milk', 'dairy', 'yogurt'],
    zhHans: ['牛奶', '酸奶'],
    zhHant: ['牛奶', '優格', '鮮奶'],
    ja: ['牛乳', 'ミルク', 'ヨーグルト'],
  ),
  EmojiKeywordEntry(
    '🥚',
    en: ['egg', 'eggs'],
    zhHans: ['鸡蛋'],
    zhHant: ['雞蛋'],
    ja: ['卵', 'たまご', '玉子'],
  ),
  EmojiKeywordEntry(
    '🍞',
    en: ['bread', 'bakery', 'toast', 'sandwich'],
    zhHans: ['面包', '吐司', '三明治', '面包店'],
    zhHant: ['麵包', '吐司', '三明治', '麵包店'],
    ja: ['パン', 'パン屋', 'トースト', 'サンドイッチ'],
  ),
  EmojiKeywordEntry(
    '🍚',
    en: ['rice'],
    zhHans: ['米饭', '大米', '买米', '煮饭'],
    zhHant: ['米飯', '白米', '買米'],
    ja: ['お米', '米', '炊飯'],
  ),
  EmojiKeywordEntry(
    '🥩',
    en: ['meat', 'steak', 'bbq', 'barbecue', 'grill'],
    zhHans: ['买肉', '牛排', '烧烤', '烤肉'],
    zhHant: ['買肉', '牛排', '燒烤', '烤肉'],
    ja: ['肉', '焼肉', 'ステーキ', 'バーベキュー'],
  ),
  EmojiKeywordEntry(
    '🍜',
    en: ['noodles', 'ramen', 'soup', 'pho', 'udon'],
    zhHans: ['面条', '拉面', '吃面', '米粉'],
    zhHant: ['麵條', '拉麵', '吃麵', '米粉'],
    ja: ['ラーメン', '麺', 'うどん', 'そば', '蕎麦'],
  ),
  EmojiKeywordEntry(
    '🍱',
    en: ['lunchbox', 'bento', 'packed lunch'],
    zhHans: ['便当', '带饭', '盒饭'],
    zhHant: ['便當', '帶便當'],
    ja: ['弁当', 'お弁当', 'べんとう', '作り置き'],
  ),
  EmojiKeywordEntry(
    '🍕',
    en: ['pizza', 'takeout', 'takeaway', 'order food', 'fast food'],
    zhHans: ['披萨', '外卖', '点外卖', '快餐'],
    zhHant: ['披薩', '外送', '叫外送', '速食'],
    ja: ['ピザ', '出前', 'デリバリー', 'テイクアウト', 'ファストフード'],
  ),
  EmojiKeywordEntry(
    '☕',
    en: ['coffee', 'cafe', 'latte', 'espresso', 'starbucks'],
    zhHans: ['咖啡', '喝咖啡', '咖啡馆', '下午茶'],
    zhHant: ['咖啡', '喝咖啡', '咖啡廳', '下午茶'],
    ja: ['コーヒー', 'カフェ', '珈琲', '喫茶店'],
  ),
  EmojiKeywordEntry(
    '🍵',
    en: ['tea', 'matcha', 'green tea'],
    zhHans: ['茶', '喝茶', '泡茶', '绿茶'],
    zhHant: ['茶', '喝茶', '泡茶', '綠茶'],
    ja: ['お茶', '緑茶', '抹茶'],
  ),
  EmojiKeywordEntry(
    '🥤',
    en: ['drink', 'drinks', 'soda', 'smoothie', 'juice', 'bubble tea', 'boba'],
    zhHans: ['饮料', '奶茶', '果汁'],
    zhHant: ['飲料', '珍奶', '手搖飲', '果汁'],
    ja: ['ジュース', '飲み物', 'タピオカ', 'スムージー'],
  ),
  EmojiKeywordEntry(
    '🍺',
    en: ['beer', 'bar', 'pub', 'drinking'],
    zhHans: ['啤酒', '喝酒', '酒吧'],
    zhHant: ['啤酒', '喝酒', '酒吧'],
    ja: ['ビール', '居酒屋', 'お酒', '乾杯'],
  ),
  EmojiKeywordEntry(
    '🍷',
    en: ['wine', 'red wine'],
    zhHans: ['红酒', '葡萄酒'],
    zhHant: ['紅酒', '葡萄酒'],
    ja: ['ワイン'],
  ),
  EmojiKeywordEntry(
    '🍰',
    en: ['dessert', 'desserts', 'sweets', 'pastry'],
    zhHans: ['甜点', '甜品'],
    zhHant: ['甜點', '甜品'],
    ja: ['スイーツ', 'デザート', 'お菓子'],
  ),

  // ── Rest and weather ──
  EmojiKeywordEntry(
    '💤',
    en: ['sleep', 'nap', 'rest', 'bedtime'],
    zhHans: ['睡觉', '午睡', '早睡', '休息', '睡眠', '补觉'],
    zhHant: ['睡覺', '午睡', '早睡', '休息', '睡眠', '補眠'],
    ja: ['寝る', '睡眠', '昼寝', '休む', '早寝', 'ねる'],
  ),
  EmojiKeywordEntry(
    '☀️',
    en: ['sunny', 'sun', 'sunscreen', 'summer'],
    zhHans: ['晴天', '防晒', '夏天', '太阳'],
    zhHant: ['晴天', '防曬', '夏天', '太陽'],
    ja: ['晴れ', '日焼け止め', '夏', '太陽'],
  ),
  EmojiKeywordEntry(
    '☔',
    en: ['umbrella', 'rain', 'rainy'],
    zhHans: ['雨伞', '带伞', '下雨'],
    zhHant: ['雨傘', '帶傘', '下雨'],
    ja: ['傘', '雨', 'かさ'],
  ),
  EmojiKeywordEntry(
    '❄️',
    en: ['snow', 'winter', 'freezer', 'defrost'],
    zhHans: ['下雪', '冬天', '冰箱'],
    zhHant: ['下雪', '冬天', '冰箱'],
    ja: ['雪', '冬', '冷凍庫', '霜取り'],
  ),

  // ── Personal items ──
  EmojiKeywordEntry(
    '🎒',
    en: ['backpack', 'school bag', 'bag'],
    zhHans: ['书包', '背包'],
    zhHant: ['書包', '背包'],
    ja: ['リュック', 'ランドセル', 'カバン'],
  ),
  EmojiKeywordEntry(
    '👟',
    en: ['shoes', 'sneakers', 'running shoes'],
    zhHans: ['鞋', '球鞋', '买鞋', '运动鞋', '刷鞋'],
    zhHant: ['鞋', '球鞋', '買鞋', '運動鞋'],
    ja: ['靴', 'スニーカー', 'くつ'],
  ),
  EmojiKeywordEntry(
    '💄',
    en: ['makeup', 'cosmetics', 'lipstick', 'beauty'],
    zhHans: ['化妆', '口红', '化妆品'],
    zhHant: ['化妝', '口紅', '化妝品'],
    ja: ['化粧', 'メイク', '口紅', '化粧品', 'コスメ'],
  ),
  EmojiKeywordEntry(
    '💎',
    en: ['diamond', 'jewelry', 'jewellery', 'luxury', 'vip', 'membership'],
    zhHans: ['钻石', '珠宝', '会员'],
    zhHant: ['鑽石', '珠寶', '會員'],
    ja: ['ダイヤ', '宝石', 'ジュエリー', '会員'],
  ),
];
